[package]
name = "hpts"
version = "0.1.0"
authors = ["hexyoungs <chuxdesign@hotmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.1"
tokio = { version = "0.2", features = ["full"] }
httparse = "1.3.4"
futures = "0.3.0"
